name: recycle_adventure
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  google_fonts: 6.1.0 #Must Use 6.1.0 or lower version. 6.2.0 will cause an error.
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.15.0
  flame_tiled: ^1.18.3
  flame_audio: ^2.1.8
  uuid: ^4.3.3
  add_to_google_wallet: ^0.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 

  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/tiles/
    - assets/images/
    - assets/images/Boss/Machine Operator/
    - assets/images/Boss/drone1/
    - assets/images/Boss/drone2/
    - assets/images/Menu/
    - assets/images/Bullets/
    - assets/images/Terrain/
    - assets/images/Objects/
    - assets/images/Background/
    - assets/images/HUD/
    - assets/images/Items/
    - assets/images/Items/Fruits/
    - assets/images/Items/Else/
    - assets/images/Items/Recycle Items/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Traps/Saw/
    - assets/images/Traps/Cars/
    - assets/images/Traps/Rock Head/
    - assets/images/Traps/Trampoline/
    - assets/images/Traps/Transporter/
    - assets/images/Traps/Hammer/
    - assets/images/Main Characters/
    - assets/images/Main Characters/Hood/
    - assets/images/Enemies/Chicken/
    - assets/images/Enemies/Slime/
    - assets/images/Enemies/Bat/
    - assets/images/Enemies/Trunk/
    - assets/images/Enemies/Cucumber/
    - assets/images/Enemies/Whale/
